// src/lib/dispositions.js

// ============================================================
// MAGNEMITE PRODUCTIVITY DISPOSITIONS
// Role / LOB / Department based disposition configuration
//
// IMPORTANT:
//
// Normal Break
// - Agent starts immediately.
// - No TL / Manager approval.
// - Stored as Break -> Scheduled Break.
//
// Excess Break
// - Never selected manually.
// - Calculated later by Magnemite from schedule variance.
//
// Extra Time Off
// - Separate employee request.
// - Requires TL / Manager approval.
// - Does NOT interrupt the employee's current status while pending.
//
// ============================================================


// ============================================================
// CONSTANTS
// ============================================================

const ALL = "*";

export const LOBS = {
  GODAY: "GoDay",
  LENDING_CREATIVE: "Lending Creative",
};

const GODAY = LOBS.GODAY;
const LENDING_CREATIVE = LOBS.LENDING_CREATIVE;

const GODAY_LC = [
  GODAY,
  LENDING_CREATIVE,
];


// ============================================================
// LEADERSHIP ROLES
//
// TL / Manager / Leadership:
// - See all manual disposition options.
// - Can approve Extra Time Off requests later.
// ============================================================

export const LEADERSHIP_ROLES = [
  "Team Leader",
  "Sr. Team Leader",
  "Manager",
  "Collector Supervisor",
  "Supervisor",
  "Q&T Manager",
  "Quality & Training Manager",
  "Business Director",
  "Executive",
  "COO",
  "Admin",
];

export function isDispositionLeadership(
  userOrRole
) {
  const rawRole =
    typeof userOrRole === "string"
      ? userOrRole
      : userOrRole?.access_level ||
        userOrRole?.role ||
        userOrRole?.title ||
        "";

  const role = String(rawRole)
    .trim()
    .toLowerCase();

  if (!role) {
    return false;
  }

  const exactMatch =
    LEADERSHIP_ROLES.some(
      (item) =>
        item.toLowerCase() === role
    );

  if (exactMatch) {
    return true;
  }

  return (
  role.includes("team leader") ||
  role.includes("manager") ||
  role.includes("supervisor") ||
  role.includes("executive") ||
  role.includes("director") ||
  role === "coo" ||
  role === "admin"
);
}


// ============================================================
// PRIMARY STATUS CONFIGURATION
//
// employeeSelectable:
//   Employee can select this status.
//
// automaticOnly:
//   Generated by Magnemite; never displayed for manual selection.
//
// leadershipOnly:
//   Only TL / Manager / Leadership can select.
// ============================================================

export const PRIMARY_STATUS_CONFIG = [
  {
    status: "Working",
    employeeSelectable: true,
  },

  {
    status: "Break",
    employeeSelectable: true,
  },

  {
    status: "Meeting",
    employeeSelectable: true,
  },

  {
    status: "Training",
    employeeSelectable: true,
  },

  {
    status: "Bathroom",
    employeeSelectable: true,
  },

  {
    status: "Coaching",
    employeeSelectable: true,
  },

  {
    status: "System Issue",
    employeeSelectable: true,
  },

  // PTO is managed through the Request workflow.
  {
    status: "PTO",
    employeeSelectable: false,
    requestOnly: true,
  },

  // VTO is managed through the Request workflow.
  {
    status: "VTO",
    employeeSelectable: false,
    requestOnly: true,
  },

  // Leadership-only manual disposition.
  {
    status: "Prize or Early Leave",
    employeeSelectable: true,
    leadershipOnly: true,
  },

  // System-generated statuses.
  {
    status: "Overtime",
    employeeSelectable: false,
    automaticOnly: true,
  },

  {
    status: "Early Unscheduled",
    employeeSelectable: false,
    automaticOnly: true,
  },

  {
    status: "Off-Day Unscheduled",
    employeeSelectable: false,
    automaticOnly: true,
  },
];

// ============================================================
// SECONDARY DISPOSITION REQUIREMENTS
//
// Break is deliberately NOT here.
//
// A regular Break does not require an extra click.
// Magnemite defaults it to Scheduled Break.
//
// Extra Time Off is handled separately as a request.
// ============================================================

export const REQUIRED_SECONDARY_STATUSES = [
  "Meeting",
  "Training",
  "Coaching",
  "System Issue",
];

export const OPTIONAL_SECONDARY_STATUSES = [
  "Working",
];

export function isSecondaryRequired(
  status
) {
  return REQUIRED_SECONDARY_STATUSES.includes(
    status
  );
}

export function isSecondaryOptional(
  status
) {
  return OPTIONAL_SECONDARY_STATUSES.includes(
    status
  );
}


// ============================================================
// DISPOSITION HELPER
// ============================================================

function disposition({
  lobs = [ALL],
  departments = [ALL],

  status,
  subStatus,

  reportingCategory,

  productive = false,
  countsInUtilization = false,

  captureMethod = "",

  showInSecondaryDropdown = true,

  automaticOnly = false,
  leadershipOnly = false,

  defaultForStatus = false,

  requiresApproval = false,

  // Request-only items do not appear in the regular
  // Status / Secondary Status workflow.
  requestOnly = false,
}) {
  return {
    lobs,
    departments,

    status,
    subStatus,

    reportingCategory,

    productive,
    countsInUtilization,

    captureMethod,

    showInSecondaryDropdown,

    automaticOnly,
    leadershipOnly,

    defaultForStatus,

    requiresApproval,
    requestOnly,

    implementationDecision:
      "Approved",
  };
}


// ============================================================
// FINAL APPROVED DISPOSITION RULES
// ============================================================

export const DISPOSITION_RULES = [

  // ==========================================================
  // WORKING - DEFAULT
  // ==========================================================

  disposition({
    lobs: GODAY_LC,
    departments: [ALL],

    status: "Working",

    subStatus:
      "Customer / Production Work",

    reportingCategory:
      "Productive",

    productive: true,

    countsInUtilization: true,

    captureMethod:
      "Default / no extra click",

    showInSecondaryDropdown:
      false,

    defaultForStatus:
      true,
  }),


  // ==========================================================
  // PTO
  // ==========================================================

  disposition({
    lobs: GODAY_LC,
    departments: [ALL],

    status: "PTO",

    subStatus:
      "Vacation / PTO",

    reportingCategory:
      "Leave",

    productive: false,

    countsInUtilization:
      false,

    captureMethod:
      "Linked to approved leave record",

    showInSecondaryDropdown:
      false,

    defaultForStatus:
      true,
  }),


  // ==========================================================
  // VTO
  // ==========================================================

  disposition({
    lobs: GODAY_LC,
    departments: [ALL],

    status: "VTO",

    subStatus:
      "Voluntary Time Off",

    reportingCategory:
      "Leave",

    productive: false,

    countsInUtilization:
      false,

    captureMethod:
      "Existing status / approval",

    showInSecondaryDropdown:
      false,

    defaultForStatus:
      true,
  }),


  // ==========================================================
  // MEETING
  // ==========================================================

  disposition({
    lobs: [ALL],
    departments: [ALL],

    status: "Meeting",

    subStatus:
      "Team Building",

    reportingCategory:
      "Auxiliary / Operational",

    productive: false,

    countsInUtilization:
      true,

    captureMethod:
      "Secondary dropdown",
  }),

  disposition({
    lobs: [ALL],
    departments: [ALL],

    status: "Meeting",

    subStatus:
      "TownHall",

    reportingCategory:
      "Auxiliary / Operational",

    productive: false,

    countsInUtilization:
      true,

    captureMethod:
      "Secondary dropdown",
  }),

  disposition({
    lobs: [ALL],
    departments: [ALL],

    status: "Meeting",

    subStatus:
      "Team Huddle",

    reportingCategory:
      "Auxiliary / Operational",

    productive: false,

    countsInUtilization:
      true,

    captureMethod:
      "Secondary dropdown",
  }),

  disposition({
    lobs: [ALL],
    departments: [ALL],

    status: "Meeting",

    subStatus:
      "1:1 / Performance Review",

    reportingCategory:
      "Auxiliary / Operational",

    productive: false,

    countsInUtilization:
      true,

    captureMethod:
      "Secondary dropdown",
  }),

  disposition({
    lobs: [ALL],
    departments: [ALL],

    status: "Meeting",

    subStatus:
      "HR / Compliance Meeting",

    reportingCategory:
      "Auxiliary / Operational",

    productive: false,

    countsInUtilization:
      true,

    captureMethod:
      "Secondary dropdown",
  }),


  // ==========================================================
  // TRAINING
  // ==========================================================

  disposition({
    lobs: [ALL],
    departments: [ALL],

    status: "Training",

    subStatus:
      "Training / Refresher",

    reportingCategory:
      "Auxiliary / Operational",

    productive: false,

    countsInUtilization:
      true,

    captureMethod:
      "Secondary dropdown",
  }),


  // ==========================================================
  // COACHING
  // ==========================================================

  disposition({
    lobs: [ALL],
    departments: [ALL],

    status: "Coaching",

    subStatus:
      "QA Coaching",

    reportingCategory:
      "Auxiliary / Operational",

    productive: false,

    countsInUtilization:
      true,

    captureMethod:
      "Secondary dropdown",
  }),

  disposition({
    lobs: [ALL],
    departments: [ALL],

    status: "Coaching",

    subStatus:
      "Performance Coaching",

    reportingCategory:
      "Auxiliary / Operational",

    productive: false,

    countsInUtilization:
      true,

    captureMethod:
      "Secondary dropdown",
  }),

  disposition({
    lobs: [ALL],
    departments: [ALL],

    status: "Coaching",

    subStatus:
      "Attendance / Schedule Coaching",

    reportingCategory:
      "Auxiliary / Operational",

    productive: false,

    countsInUtilization:
      true,

    captureMethod:
      "Secondary dropdown",
  }),


  // ==========================================================
  // SYSTEM ISSUE
  // ==========================================================

  disposition({
    lobs: [ALL],
    departments: [ALL],

    status: "System Issue",

    subStatus:
      "Infinity",

    reportingCategory:
      "System Loss",

    productive: false,

    countsInUtilization:
      false,

    captureMethod:
      "Secondary dropdown + optional ticket",
  }),

  disposition({
    lobs: [ALL],
    departments: [ALL],

    status: "System Issue",

    subStatus:
      "uContact",

    reportingCategory:
      "System Loss",

    productive: false,

    countsInUtilization:
      false,

    captureMethod:
      "Secondary dropdown + optional ticket",
  }),

  disposition({
    lobs: [ALL],
    departments: [ALL],

    status: "System Issue",

    subStatus:
      "Internet / Connectivity",

    reportingCategory:
      "System Loss",

    productive: false,

    countsInUtilization:
      false,

    captureMethod:
      "Secondary dropdown + optional note",
  }),

  disposition({
    lobs: [ALL],
    departments: [ALL],

    status: "System Issue",

    subStatus:
      "Computer / Hardware",

    reportingCategory:
      "System Loss",

    productive: false,

    countsInUtilization:
      false,

    captureMethod:
      "Secondary dropdown + optional ticket",
  }),

  disposition({
    lobs: [ALL],
    departments: [ALL],

    status: "System Issue",

    subStatus:
      "Access / Credentials",

    reportingCategory:
      "System Loss",

    productive: false,

    countsInUtilization:
      false,

    captureMethod:
      "Secondary dropdown + optional ticket",
  }),


  // ==========================================================
  // WORKING - DOCUMENTS / CLS
  // ==========================================================

  disposition({
    lobs: [ALL],

    departments: [
      "Documents",
      "CLS",
    ],

    status: "Working",

    subStatus:
      "Back Office / Documents",

    reportingCategory:
      "Productive",

    productive: true,

    countsInUtilization:
      true,

    captureMethod:
      "Optional secondary reason",
  }),

  disposition({
    lobs: [GODAY],

    departments: [
      "Documents",
      "CLS",
    ],

    status: "Working",

    subStatus:
      "Posting Checks",

    reportingCategory:
      "Productive",

    productive: true,

    countsInUtilization:
      true,

    captureMethod:
      "Optional secondary reason",
  }),


  // ==========================================================
  // WORKING - GODAY CLS
  // ==========================================================

  disposition({
    lobs: [GODAY],

    departments: [
      "CLS",
    ],

    status: "Working",

    subStatus:
      "Posting EMT",

    reportingCategory:
      "Productive",

    productive: true,

    countsInUtilization:
      true,

    captureMethod:
      "Optional secondary reason",
  }),

  disposition({
    lobs: [GODAY],

    departments: [
      "CLS",
    ],

    status: "Working",

    subStatus:
      "Returns",

    reportingCategory:
      "Productive",

    productive: true,

    countsInUtilization:
      true,

    captureMethod:
      "Optional secondary reason",
  }),


  // ==========================================================
  // WORKING - EMAILS
  // ==========================================================

  disposition({
    lobs: [ALL],

    departments: [
      "Emails",
    ],

    status: "Working",

    subStatus:
      "Emails/Chats/SMS",

    reportingCategory:
      "Productive",

    productive: true,

    countsInUtilization:
      true,

    captureMethod:
      "Optional secondary reason",
  }),


  // ==========================================================
  // WORKING - LC CUSTOMER SERVICE
  // ==========================================================

  disposition({
    lobs: [
      LENDING_CREATIVE,
    ],

    departments: [
      "CS",
    ],

    status: "Working",

    subStatus:
      "Calls",

    reportingCategory:
      "Productive",

    productive: true,

    countsInUtilization:
      true,

    captureMethod:
      "Optional secondary reason",
  }),


  // ==========================================================
  // WORKING - COLLECTIONS
  // ==========================================================

  disposition({
    lobs: GODAY_LC,

    departments: [
      "Collector",
    ],

    status: "Working",

    subStatus:
      "Collections",

    reportingCategory:
      "Productive",

    productive: true,

    countsInUtilization:
      true,

    captureMethod:
      "Optional secondary reason",
  }),


  // ==========================================================
  // WORKING - LC RETURNING
  // ==========================================================

  disposition({
    lobs: [
      LENDING_CREATIVE,
    ],

    departments: [
      "RET",
    ],

    status: "Working",

    subStatus:
      "Calls / Emails/Chats/SMS",

    reportingCategory:
      "Productive",

    productive: true,

    countsInUtilization:
      true,

    captureMethod:
      "Optional secondary reason",
  }),


  // ==========================================================
  // WORKING - LC LO
  // ==========================================================

  disposition({
    lobs: [
      LENDING_CREATIVE,
    ],

    departments: [
      "LO",
    ],

    status: "Working",

    subStatus:
      "Processing",

    reportingCategory:
      "Productive",

    productive: true,

    countsInUtilization:
      true,

    captureMethod:
      "Optional secondary reason",
  }),


  // ==========================================================
  // WORKING - GODAY CS/LO
  // ==========================================================

  disposition({
    lobs: [
      GODAY,
    ],

    departments: [
      "CS/LO",
    ],

    status: "Working",

    subStatus:
      "Processing / Customer Communication",

    reportingCategory:
      "Productive",

    productive: true,

    countsInUtilization:
      true,

    captureMethod:
      "Optional secondary reason",
  }),

  disposition({
    lobs: [
      GODAY,
    ],

    departments: [
      "CS/LO",
    ],

    status: "Working",

    subStatus:
      "Retention",

    reportingCategory:
      "Productive",

    productive: true,

    countsInUtilization:
      true,

    captureMethod:
      "Optional secondary reason",
  }),


  // ==========================================================
  // WORKING - PROJECT / ASSIGNED TASK
  // ==========================================================

  disposition({
    lobs: [ALL],
    departments: [ALL],

    status: "Working",

    subStatus:
      "Project / Assigned Task",

    reportingCategory:
      "Productive",

    productive: true,

    countsInUtilization:
      true,

    captureMethod:
      "Optional secondary reason",
  }),


  // ==========================================================
  // BREAK - NORMAL SCHEDULED BREAK
  //
  // Employee clicks Break normally.
  // No approval.
  // No extra dropdown.
  // ==========================================================

  disposition({
    lobs: GODAY_LC,
    departments: [ALL],

    status: "Break",

    subStatus:
      "Scheduled Break",

    reportingCategory:
      "Break",

    productive: false,

    countsInUtilization:
      false,

    captureMethod:
      "Agent selection / available scheduled break",

    showInSecondaryDropdown:
      false,

    automaticOnly:
      false,

    requiresApproval:
      false,

    requestOnly:
      false,

    defaultForStatus:
      true,
  }),


  // ==========================================================
  // BREAK - EXCESS BREAK
  //
  // Employee does NOT select this.
  // Magnemite calculates this from schedule variance.
  // ==========================================================

  disposition({
    lobs: GODAY_LC,
    departments: [ALL],

    status: "Break",

    subStatus:
      "Excess Break",

    reportingCategory:
      "Personal / Variance",

    productive: false,

    countsInUtilization:
      false,

    captureMethod:
      "Calculated automatically from schedule variance",

    showInSecondaryDropdown:
      false,

    automaticOnly:
      true,

    requiresApproval:
      false,

    requestOnly:
      false,
  }),


  // ==========================================================
  // EXTRA TIME OFF
  //
  // IMPORTANT:
  //
  // This is NOT a normal Break selection.
  //
  // Employee submits a request.
  // TL / Manager approves or rejects.
  //
  // While pending:
  // - Employee remains in current status.
  //
  // After approval:
  // - Can later be recorded/reported as:
  //   Break -> Extra Time Off.
  // ==========================================================

  disposition({
    lobs: GODAY_LC,
    departments: [ALL],

    status: "Break",

    subStatus:
      "Extra Time Off",

    reportingCategory:
      "Personal / Variance",

    productive: false,

    countsInUtilization:
      false,

    captureMethod:
      "Agent request + TL/Manager approval",

    showInSecondaryDropdown:
      false,

    automaticOnly:
      false,

    requiresApproval:
      true,

    requestOnly:
      true,
  }),


  // ==========================================================
  // BATHROOM
  // ==========================================================

  disposition({
    lobs: GODAY_LC,
    departments: [ALL],

    status: "Bathroom",

    subStatus:
      "Bathroom",

    reportingCategory:
      "Personal / Non-Productive",

    productive: false,

    countsInUtilization:
      false,

    captureMethod:
      "Existing status; calculate duration/frequency",

    showInSecondaryDropdown:
      false,

    defaultForStatus:
      true,
  }),


  // ==========================================================
  // PRIZE / EARLY LEAVE
  //
  // Leadership-only.
  // ==========================================================

  disposition({
    lobs: GODAY_LC,
    departments: [ALL],

    status:
      "Prize or Early Leave",

    subStatus:
      "Approved time off by TL/Manager",

    reportingCategory:
      "Non-Productive",

    productive: false,

    countsInUtilization:
      false,

    captureMethod:
      "TL / Manager selection",

    showInSecondaryDropdown:
      false,

    leadershipOnly:
      true,

    defaultForStatus:
      true,
  }),
];


// ============================================================
// NORMALIZATION
// ============================================================

export function normalizeLob(lob) {
  const value =
    String(lob || "").trim();

  const lower =
    value.toLowerCase();

  if (
    lower === "lc" ||
    lower === "lending creative" ||
    lower === "lendingcreative"
  ) {
    return LENDING_CREATIVE;
  }

  if (
    lower === "goday" ||
    lower === "go day"
  ) {
    return GODAY;
  }

  return value;
}


export function normalizeDepartment(
  department
) {
  const value =
    String(department || "").trim();

  const lower =
    value.toLowerCase();

  const aliases = {
    "customer service": "CS",

    "customer service / loan officer":
      "CS/LO",

    "cs / lo":
      "CS/LO",

    "cs/lo":
      "CS/LO",

    collections:
      "Collector",

    collector:
      "Collector",

    "loan officer":
      "LO",

    lo:
      "LO",

    returning:
      "RET",

    "returning customer":
      "RET",

    ret:
      "RET",

    documents:
      "Documents",

    emails:
      "Emails",

    cls:
      "CLS",
  };

  return aliases[lower] || value;
}


// ============================================================
// LOB / DEPARTMENT MATCHING
// ============================================================

function matchesLob(
  rule,
  lob
) {
  if (
    rule.lobs.includes(ALL)
  ) {
    return true;
  }

  const normalizedLob =
    normalizeLob(lob);

  return rule.lobs
    .map(normalizeLob)
    .includes(
      normalizedLob
    );
}


function matchesDepartment(
  rule,
  department
) {
  if (
    rule.departments.includes(
      ALL
    )
  ) {
    return true;
  }

  const normalizedDepartment =
    normalizeDepartment(
      department
    );

  return rule.departments
    .map(
      normalizeDepartment
    )
    .includes(
      normalizedDepartment
    );
}


// ============================================================
// PRIMARY STATUS VISIBILITY
// ============================================================

export function getAvailablePrimaryStatuses(
  user
) {
  const leadership =
    isDispositionLeadership(
      user
    );

  return PRIMARY_STATUS_CONFIG
    .filter((item) => {
      if (
        !item.employeeSelectable
      ) {
        return false;
      }

      if (
        item.leadershipOnly &&
        !leadership
      ) {
        return false;
      }

      return true;
    })
    .map(
      (item) =>
        item.status
    );
}


// ============================================================
// NORMAL SECONDARY DROPDOWN
//
// IMPORTANT:
//
// requestOnly items are excluded.
//
// Therefore:
//
// Break -> Extra Time Off
//
// will NOT appear inside the normal Break workflow.
// ============================================================

export function getAvailableSubStatuses({
  status,
  lob,
  department,
  role,
  accessLevel,
  user,
}) {
  const leadership =
    isDispositionLeadership(
      user ||
      accessLevel ||
      role
    );

  let rules =
    DISPOSITION_RULES.filter(
      (rule) =>
        rule.status === status &&
        rule.showInSecondaryDropdown &&
        !rule.automaticOnly &&
        !rule.requestOnly
    );

  // Leadership sees all normal manual options.
  if (!leadership) {
    rules =
      rules.filter(
        (rule) =>
          matchesLob(
            rule,
            lob
          ) &&
          matchesDepartment(
            rule,
            department
          ) &&
          !rule.leadershipOnly
      );
  }

  return [
    ...new Set(
      rules.map(
        (rule) =>
          rule.subStatus
      )
    ),
  ];
}


// ============================================================
// REQUESTABLE DISPOSITIONS
//
// Used later by App.jsx for things such as:
//
// [ Request Extra Time Off ]
//
// This is deliberately separate from normal status changes.
// ============================================================

export function getRequestableDispositions({
  lob,
  department,
  role,
  accessLevel,
  user,
}) {
  const leadership =
    isDispositionLeadership(
      user ||
      accessLevel ||
      role
    );

  let rules =
    DISPOSITION_RULES.filter(
      (rule) =>
        rule.requestOnly &&
        !rule.automaticOnly
    );

  if (!leadership) {
    rules =
      rules.filter(
        (rule) =>
          matchesLob(
            rule,
            lob
          ) &&
          matchesDepartment(
            rule,
            department
          ) &&
          !rule.leadershipOnly
      );
  }

  return rules.map(
    (rule) => ({
      status:
        rule.status,

      subStatus:
        rule.subStatus,

      requiresApproval:
        rule.requiresApproval,

      reportingCategory:
        rule.reportingCategory,

      captureMethod:
        rule.captureMethod,
    })
  );
}


// ============================================================
// DEFAULT SECONDARY STATUS
//
// Used when the user should not need an extra click.
//
// Examples:
//
// Working
// -> Customer / Production Work
//
// Break
// -> Scheduled Break
//
// PTO
// -> Vacation / PTO
//
// VTO
// -> Voluntary Time Off
//
// Bathroom
// -> Bathroom
// ============================================================

export function getDefaultSubStatus(
  status
) {
  const defaultRule =
    DISPOSITION_RULES.find(
      (rule) =>
        rule.status ===
          status &&
        rule.defaultForStatus
    );

  return (
    defaultRule?.subStatus ||
    null
  );
}


// ============================================================
// APPROVAL CHECK
// ============================================================

export function dispositionRequiresApproval({
  status,
  subStatus,
}) {
  const rule =
    DISPOSITION_RULES.find(
      (item) =>
        item.status ===
          status &&
        item.subStatus ===
          subStatus
    );

  return Boolean(
    rule?.requiresApproval
  );
}


// ============================================================
// REQUEST-ONLY CHECK
// ============================================================

export function isRequestOnlyDisposition({
  status,
  subStatus,
}) {
  const rule =
    DISPOSITION_RULES.find(
      (item) =>
        item.status ===
          status &&
        item.subStatus ===
          subStatus
    );

  return Boolean(
    rule?.requestOnly
  );
}


// ============================================================
// AUTOMATIC DISPOSITION CHECK
// ============================================================

export function isAutomaticDisposition({
  status,
  subStatus,
}) {
  const rule =
    DISPOSITION_RULES.find(
      (item) =>
        item.status ===
          status &&
        item.subStatus ===
          subStatus
    );

  return Boolean(
    rule?.automaticOnly
  );
}


// ============================================================
// REPORTING METADATA
// ============================================================

export function getDispositionReportingMeta({
  status,
  subStatus,
}) {
  let rule = null;

  if (subStatus) {
    rule =
      DISPOSITION_RULES.find(
        (item) =>
          item.status ===
            status &&
          item.subStatus ===
            subStatus
      );
  }

  if (!rule) {
    rule =
      DISPOSITION_RULES.find(
        (item) =>
          item.status ===
            status &&
          item.defaultForStatus
      );
  }

  if (!rule) {
    return {
      reportingCategory:
        "Unclassified",

      productive:
        false,

      countsInUtilization:
        false,

      requiresApproval:
        false,

      requestOnly:
        false,

      automaticOnly:
        false,
    };
  }

  return {
    reportingCategory:
      rule.reportingCategory,

    productive:
      rule.productive,

    countsInUtilization:
      rule.countsInUtilization,

    requiresApproval:
      rule.requiresApproval,

    requestOnly:
      rule.requestOnly,

    automaticOnly:
      rule.automaticOnly,
  };
}


// ============================================================
// SYSTEM ISSUE HELPERS
// ============================================================

export function isSystemIssue(
  status
) {
  return (
    status ===
    "System Issue"
  );
}


export function shouldShowDispositionNote(
  status
) {
  return (
    status ===
    "System Issue"
  );
}


// ============================================================
// VALIDATION
// ============================================================

export function validateDisposition({
  status,
  subStatus,
}) {
  if (!status) {
    return {
      valid: false,
      message:
        "Select a status.",
    };
  }

  if (
    isSecondaryRequired(
      status
    ) &&
    !subStatus
  ) {
    return {
      valid: false,
      message:
        "Please select a reason.",
    };
  }

  return {
    valid: true,
    message: "",
  };
}